name: Build Andriod
on:
  workflow_dispatch: {}
jobs:
  Build_Andriod:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: 构建Java环境
        uses: actions/setup-java@v3
        with:
                  distribution: "zulu"
                  java-version: "17"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --release --split-per-abi
      
      - uses: actions/upload-artifact@v3
        with:
          name: app-arm64-v8a-release.apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk


